In [2]:
arr = np.arange(6)

In [3]:
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
import numpy as np

# Creating two sample arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Element-wise multiplication
elementwise_result = arr1 * arr2

# Matrix multiplication
matrix_result = np.dot(arr1, arr2)

elementwise_result, matrix_result


(array([[ 5, 12],
        [21, 32]]),
 array([[19, 22],
        [43, 50]]))

In [21]:
arr3 = np.array([[2,1],[4,5],[5,6]])
arr4 = np.array([[4,3,2],[2,1,2]])

In [27]:
x = np.dot(arr3.T * arr4)

TypeError: dot() missing 1 required positional argument: 'b'

In [29]:
import numpy as np

arr3 = np.array([[2, 1], [4, 5], [5, 6]])
arr4 = np.array([[4, 3, 2], [2, 1, 2]])

# Transpose arr4 to make the multiplication valid
x = np.dot(arr4, arr3.T)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [31]:
import numpy as np

arr3 = np.array([[2, 1], [4, 5], [5, 6]])
arr4 = np.array([[4, 3, 2], [2, 1, 2]])

# Transpose arr3 to make the multiplication valid
x = np.dot(arr4, arr3)


In [42]:
arr1 = np.linspace(0,1,9)


In [51]:
arr1.reshape(3,3)

array([[0.   , 0.125, 0.25 ],
       [0.375, 0.5  , 0.625],
       [0.75 , 0.875, 1.   ]])

In [52]:
arr1

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [53]:
arr

array([[0, 1],
       [2, 3],
       [4, 5]])